import SwiftUI

public struct EndpointEnrichmentView: View {
    @StateObject private var model = EndpointEnrichmentViewModel()
    public init() {}
    public var body: some View { ZStack { AppBackground(); ScrollView { VStack(alignment: .leading, spacing: 14) {
        Text("Endpoint Enrichment").font(.title2.weight(.semibold)); Text("Cached reverse DNS, ASN, RDAP, reputation context, and user-triggered TLS certificate inspection.").foregroundStyle(.secondary)
        GlassCard { VStack(alignment: .leading, spacing: 9) { Text("IP Context").font(.headline); HStack { TextField("Public IPv4 address", text: $model.address).textFieldStyle(.roundedBorder); Button("Lookup") { Task { await model.enrich() } }.disabled(model.working || model.address.isEmpty); Button("Refresh") { Task { await model.enrich(refresh: true) } }.disabled(model.working || model.address.isEmpty) }; Text("Results expire after 24 hours. RDAP contacts rdap.org; ASN and PTR use DNS. Provider privacy settings still apply.").font(.caption).foregroundStyle(.secondary) } }
        ForEach(model.records) { item in GlassCard { VStack(alignment: .leading, spacing: 5) { HStack { Text(item.address).font(.headline.monospaced()); Spacer(); Text("Risk \(item.riskScore)/100 · \(item.riskLabel)").font(.caption.monospacedDigit()) }; LabeledContent("Reverse DNS", value: item.reverseDNS ?? "Unavailable"); LabeledContent("ASN", value: item.asn ?? "Unavailable"); LabeledContent("RDAP", value: item.rdap ?? "Unavailable"); Text("Checked \(item.checkedAt.formatted()) · Expires \(item.expiresAt.formatted())").font(.caption2).foregroundStyle(.secondary) } } }
        GlassCard { VStack(alignment: .leading, spacing: 9) { Text("TLS Certificate Viewer").font(.headline); HStack { TextField("Hostname", text: $model.tlsHost).textFieldStyle(.roundedBorder); TextField("Port", text: $model.tlsPort).frame(width: 80).textFieldStyle(.roundedBorder); Button("Inspect TLS") { Task { await model.inspectTLS() } }.disabled(model.working || model.tlsHost.isEmpty) }; Text("Performs a normal direct TLS handshake only. No interception, decryption, trust installation, or payload capture.").font(.caption).foregroundStyle(.secondary); if let tls = model.tls { LabeledContent("Subject", value: tls.subject ?? "Unavailable"); LabeledContent("Issuer", value: tls.issuer ?? "Unavailable"); LabeledContent("Valid from", value: tls.notBefore ?? "Unavailable"); LabeledContent("Expires", value: tls.notAfter ?? "Unavailable"); LabeledContent("SHA-256", value: tls.sha256Fingerprint ?? "Unavailable"); LabeledContent("Protocol", value: tls.protocolVersion ?? "Unavailable"); LabeledContent("Cipher", value: tls.cipher ?? "Unavailable") } } }
        if let error = model.error { Text(error).font(.caption).foregroundStyle(.red) }
    }.padding(16) } }.task { await model.load() } }
}
