import SwiftUI

public struct InvestigationWorkflowView: View {
    @ObservedObject private var network: ApplicationNetworkViewModel; @StateObject private var annotations = NetworkContextAnnotationStore(); @StateObject private var model = InvestigationWorkflowViewModel(); @State private var watchAddress = ""
    public init(network: ApplicationNetworkViewModel) { self.network = network }
    public var body: some View { ZStack { AppBackground(); ScrollView { VStack(alignment: .leading, spacing: 14) {
        Text("Investigation Workflow").font(.title2.weight(.semibold)); Text("Watchlists, local reports, and explicit retention controls.").foregroundStyle(.secondary)
        GlassCard { VStack(alignment: .leading, spacing: 9) { HStack { Text("Watchlist").font(.headline); Spacer(); TextField("IP or context key", text: $watchAddress).textFieldStyle(.roundedBorder).frame(width: 240); Button("Add") { let value = watchAddress.trimmingCharacters(in: .whitespacesAndNewlines); if !value.isEmpty { annotations.setWatched(true, for: value); watchAddress = "" } } }; if watchedKeys.isEmpty { Text("No watched destinations.").foregroundStyle(.secondary) }; ForEach(watchedKeys, id: \.self) { key in let annotation = annotations.annotation(for: key); HStack { Image(systemName: "eye.fill").foregroundStyle(.orange); VStack(alignment: .leading) { Text(key).font(.subheadline.monospaced()); Text(annotation.note.isEmpty ? "No note" : annotation.note).font(.caption).foregroundStyle(.secondary) }; Spacer(); let observations = network.timelineHistory.filter { $0.remoteAddress == key }.count; Text("\(observations) loaded observations").font(.caption.monospacedDigit()); Button("Remove") { annotations.setWatched(false, for: key) }.buttonStyle(.borderless) } } } }
        GlassCard { VStack(alignment: .leading, spacing: 9) { HStack { Text("Daily Local Reports").font(.headline); Spacer(); Button("Generate Today") { Task { await model.generate(records: network.timelineHistory) } } }; ForEach(model.reports.prefix(14)) { report in DisclosureGroup("\(report.periodStart.formatted(date: .long, time: .omitted)) — \(report.observations) observations") { Text("Processes \(report.processes) · Destinations \(report.destinations) · Countries \(report.countries) · Blocked \(report.blocked)\nNew processes: \(report.newProcesses.joined(separator: ", "))\n\n\(report.journal)").font(.caption).textSelection(.enabled) } }; Text("One report is generated per day while GlossWire runs. Reports remain local and Disable all logs prevents persistence.").font(.caption).foregroundStyle(.secondary) } }
        GlassCard { VStack(alignment: .leading, spacing: 9) { Text("History Retention").font(.headline); HStack { Stepper("Retain \(model.retentionDays) days", value: $model.retentionDays, in: 1...365); Spacer(); Text("\(model.retainedCount.formatted()) records currently retained").font(.caption.monospacedDigit()); Button("Prune and Compact", role: .destructive) { Task { await model.applyRetention(network: network) } } }; Text("Pruning permanently deletes connection history older than the selected age and compacts SQLite. Application rules and annotations are not deleted.").font(.caption).foregroundStyle(.orange); if let message = model.message { Text(message).font(.caption).foregroundStyle(.secondary) } } }
    }.padding(16) } }.task { network.start(); network.setTimelineWindow(.all); await network.reloadTimeline(); await model.load(network: network); await model.generateDailyIfNeeded(records: network.timelineHistory) } }
    private var watchedKeys: [String] { annotations.annotations.filter { $0.value.isWatched }.map(\.key).sorted() }
}
